### ISSUE TITLE
antenna setup

### ISSUE THREAD

**Issue by ispeakastronomy** [30hours/blah2#3]
Can you give me some help with your antenna setup? Did you use one or two? How did you orient them, what type of antenna, etc? Thx

**Comment by 30hours** [comment]
2 antennas, 1 for the reference (generally pointed at the transmitter) and the surveillance (roughly pointed in the area you wish to get targets in). In an urban area a directional reference antenna is not needed since the tv/radio signals are so strong, so I use a telescopic monopole antenna (the one that comes with the RTL-SDR). For the surveillance I have a directional Yagi with around 13 dBi of gain. I designed and built this antenna specifically for the DAB frequency of 204.64 MHz - although any (somewhat directional) surveillance antenna should work fine. I have a work in progress blog post which describes my antenna setup for reference; [https://mrgood.blog/posts/2023-08-01-design-op-passive-radar/post.html](https://mrgood.blog/posts/2023-08-01-design-op-passive-radar/post.html).
