### ISSUE TITLE
README.md has a reference to a missing file

### ISSUE THREAD

**Issue by sdn-ninja** [30hours/blah2#8]
In README.md under Usage, there is a reference for ./lib/sdrplay-3.12.1/install_lib.sh
this file isn't available under that directory. 

I think it was located in the top directory (as of last week), but has been removed? I was going to create a PR to move it to ./lib/sdrplay* .. but it has been taken out completely.

P.S. it would be great if you create a new tag for every release so we can track diffs

**Comment by 30hours** [comment]
Good pickup! This file gets extracted when you run the previous line in the README:
`./lib/sdrplay-3.12.1/SDRplay_RSP_API-Linux-3.12.1.run --tar -xvf -C ./lib/sdrplay-3.12.1`
Since it gets extracted I removed it from the repo.

Will definitely start doing tags soon - still adding some core functionality and want to commit freely.
